version: "3.9"  
services:
  app:
    build: .
    ports:
      - "8082:8080"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/v2/api-docs"]
        interval: 30s
        timeout: 10s
        retries: 10
  Zap-scan:
    image: owasp/zap2docker-weekly
    container_name: zap
    command:
      zap-api-scan.py
      -t http://app:8080/v2/api-docs -f openapi 
      -r report.html
    volumes:
      - .:/zap/wrk
    depends_on:
      app:
        condition: "service_healthy"
